### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by CCurl** [sehugg/8bitworkshop#89]
I am trying to write an assembler program for x86.

I'd like to define a buffer of 64 bytes, but the assembler doesn't like:

tib db 64 dup(0)

How do I define a buffer?

**Comment by CCurl** [comment]
I don't need anyone to fix anything, just looking for info. What assembler is it?

**Comment by sehugg** [comment]
The assembler is YASM, which uses NASM syntax: http://www.tortall.net/projects/yasm/manual/html/nasm-pseudop.html#nasm-pseudop-db

Since x86 uses segments you'd have to use the xss segment for uninitialized data:

    section .bss
    tib: resb 64

I believe all segment registers are set to the same value (so you're limited to 64k)

**Comment by CCurl** [comment]
Thanks!
