### ISSUE TITLE
Github integration broken

### ISSUE THREAD

**Issue by duckyvirus** [sehugg/8bitworkshop#97]
Cannot sign-in, commit or import from GitHub.  Chrome Version 98.0.4758.82 (Official Build) (64-bit)

shutdown server, pulled any updates and rebuilt, no change.  completely cleared browser cache, no change.

**Comment by micahcowan** [comment]
I'm not experiencing that issue with current 8bitworkshop.com/dev/ (as of hours ago, which is running a bleeding-edge instance of current "master"). I'm running 97.0.4692.99 (Official Build) (64-bit), Windows 11.

What do you mean by "shutdown server"? You were running your own instance locally on your machine? Github integration won't work outside of 8bitworkshop.com itself, without API keys (for both Github and Firebase) in a custom config.js script. Don't expect that to work in a local instance without some work (@sehugg, a guide or some pointers on how to set that up for private instances wouldn't go amiss - I'd be interested in the process, particularly the Firebase stuff as I'm not familiar with it)

**Comment by micahcowan** [comment]
(I may have done the actual sign-in to Github via `/v3.9.0/` and not `/dev/`, but it was `/dev/` I was successfully pulling and pushing on a least. Anyway it sounds like you were likely using neither.)

**Comment by sehugg** [comment]
For GitHub to work locally you do have to use Firebase Auth (unless you hack it somehow)

The easiest way is to download the config file and put that in the root directory: https://8bitworkshop.com/v3.9.0/config.js

I should add this to the README.

**Comment by micahcowan** [comment]
Doesn't encouraging use of your own API keys for that purpose, run the risk of getting blocked because of what someone else may do with them? Also Github pull access seems to be severely rate-limited if one isn't signed in, which will presumably be worse if more people are using those keys (but I guess that just means "don't pull without signing in", heh).

A brief walkthrough on how to generate one's own config.js would be useful (in addition to the "copy our config.js" nod in a README) - I'm sure I could figure out at least the Github portion, but I wasn't sure if I need to set up a particular app or featureset on Firebase, or if it's enough just to create a user account and then generate keys?

**Comment by sehugg** [comment]
I think there's a limit of 10K auths/month for free, right now not even close to the limit.

You could also create your own Firebase project and [configuration](https://support.google.com/firebase/answer/7015592?hl=en#web&zippy=%2Cin-this-article) but there's no real benefit in doing so.

**Comment by sehugg** [comment]
Easy fix: I just made it load the config.js from 8bitworkshop.com (of course you can override locally if you wish)

This also makes the new Github build work without checking in files: https://sehugg.github.io/8bitworkshop/
